### ISSUE TITLE
How to host logs panel on replit

### ISSUE THREAD

**Issue by wolfier74** [discord-tickets/bot#105]
Hello can you make guide how to host web portal for logs on replit?

**Comment by eartharoid** [comment]
I haven't tried, but I assume it would be the same.

**Comment by wolfier74** [comment]
Ok, so I need to rewrite donetv config. Also why .env is located in /user

**Comment by eartharoid** [comment]
I put the env file in `user/` because I wanted all of the files that you might want to/need to interact with to be together as the root is cluttered with other dotfiles.
