### ISSUE TITLE
Add that ticket logs will be uploaded to pastebin/hastebin.

### ISSUE THREAD

**Issue by wolfier74** [discord-tickets/bot#106]
Hello, can you add option to upload ticket transcripts to pastebin/hastebin? Instead of sending text file to Discord you can just send link to paste/haste and save it to database. Its annoying to download text file when you need to check ticket logs.

**Comment by wolfier74** [comment]
You can use https://www.npmjs.com/package/@catte_/pastebin.js and https://www.npmjs.com/package/hastebin.js

**Comment by FatGrizzly** [comment]
This is nice, but all the ticket stuff will be publicly available on the internet and that would violate Discord's TOS

**Comment by wolfier74** [comment]
Yes but I dont think that someone will find it. On hastebin there is no search and on pastebin you can make unlisted and private pastes.

**Comment by Sarveshmrao** [comment]
@wolfier74 I wonder why you need to put that in paste or hastebin.
There is a DiscordTickets-Portal Repo. Just self host that. It'll look professional. It'll give you a link when the ticket gets closed. Click that and read the convo with similar UI as Discord.

**Comment by wolfier74** [comment]
@Sarveshmrao On portal there are logs public too. There is no oauth protection. Everyone can view logs. And also its annoying to always download text file from Discord to check ticket logs, the hastebin/pastebin option for logs will solve this, not everyone needs hosting additional portal.

**Comment by Sarveshmrao** [comment]
> @Sarveshmrao On portal there are logs public too. There is no oauth protection. Everyone can view logs. And also its annoying to always download text file from Discord to check ticket logs, the hastebin/pastebin option for logs will solve this, not everyone needs to host additional portal.

@wolfier74 the tickets in the portal can only be accessed using the URL given. It's not picked up by the crawlers. Also the ticket is uploaded to the portal only after after ticket is closed. I know that downloading text file that too on mobile is pretty annoying thats the reason for for Portal. Also portal doesn't need a OAuth Authentication. As it'll make the setup more difficult. But anyone with the URL to the ticket can access it. It also has an option to delete the tickets after X time. I guess portal is the best option.

**Comment by eartharoid** [comment]
I am planning on adding oauth to the portal.

**Comment by wolfier74** [comment]
Will you also add hastebin/paatebin option?

**Comment by FatGrizzly** [comment]
Well, no one wants to upload their tickets/chats to pastebin/hastebin... You can implement yourself tho

**Comment by eartharoid** [comment]
I'd prefer to make text transcripts part of the portal instead of uploading them to a third party.

**Comment by ririko5834** [comment]
>>> I'd prefer to make text transcripts part of the portal instead of uploading them to a third party, but I might add this as an option for those that don't want to host the portal.

Ok this is good, that users can choose if they want to use portal text transcripts or upload them to pastebin/hastebin

**Comment by eartharoid** [comment]
As Discord now shows the contents of plain text files in the UI is this still necessary? You can read the transcript on Discord without needing to download and open the file.

**Comment by wolfier74** [comment]
Yes, on mobile you cannot view it.
Also it will be better when the bot will send embed with details to log channel when ticket was opened, claimed, renamed, user added, user removed, topic changed and ticket closed. When ticket was closed, add embed field with link to hastebin logs

**Comment by anondev-sudo** [comment]
I agree with this, the portal should be created and option to upload the logs to hastebin.com would be nice too

**Comment by anondev-sudo** [comment]
Maybe the portal should be part of the bot itself, and it should be option so you don't have to enable it

**Comment by eartharoid** [comment]
Support for uploading to third parties will not be added as there is no guarantee of security and it would be difficult for a user to get their data deleted.
