### ISSUE TITLE
Bot does not start

### ISSUE THREAD

**Issue by kittylegitcheck** [discord-tickets/bot#119]
**Describe the bug**
Bot just does not work

**To Reproduce**
Steps to reproduce the behaviour:
Setup bot?

**Expected behavior**
Bot should work

**Screenshots**
![image](https://user-images.githubusercontent.com/79789524/109471417-047b1380-7a71-11eb-8570-76694d30ce15.png)

**Additional context**

**Comment by Tropixi** [comment]
Same issue here brother

**Comment by Sarveshmrao** [comment]
Join the discord server and read #faq channel. It has solution to this. @kittylegitcheck and @Tropixi

**Comment by eartharoid** [comment]
> Same issue here brother

This error is caused by not properly configuring the bot or not adding the bot to your Discord server.
