### ISSUE TITLE
Undefinited

### ISSUE THREAD

**Issue by Kathou99** [discord-tickets/bot#122]
**Describe the bug**
He has two ''bug'' 
`Uncaught TypeError: Cannot read property 'member' of undefined`
`[12:00:46 | WARN] An error was not caught
[12:00:46 | WARN] Uncaught TypeError: Cannot read property 'id' of undefined`

**To Reproduce**
run the help command 

**Expected behavior**
to see the help command

**Comment by eartharoid** [comment]
Either:
- You haven't added the bot to your server, or
- You haven't fully [configured the bot](https://github.com/discord-tickets/bot/wiki/Configuration#notice)

**Comment by Kathou99** [comment]
-The bot is in my server and online
-I my config is full 
The error I get now is [12:18:28 | WARN] Uncaught TypeError: Cannot read property 'get' of undefined

**Comment by Kathou99** [comment]
Can you help my in discord? I want to have the option to add four role of my staff team and I want to be able to have there ticket panel and separate logs...kathouQC#3838 discord

**Comment by eartharoid** [comment]
![screenshot](https://i.imgur.com/JrKgs5x.png)

Could you join the [support server](https://go.eartharoid.me/discord)?

**Comment by Kathou99** [comment]
🌷🎀𝒦𝒶𝓉𝒽𝑜𝓊𝒬𝒞🎀💎#3838
