### ISSUE TITLE
Bug with rename and topic

### ISSUE THREAD

**Issue by QuintenQVD0** [discord-tickets/bot#141]
**Describe the bug**
You can only rename or set the topic 1 time if you try it a second time it won't do it and (you try it the second time to rename of topic ) closing no longer works
**To Reproduce**
1.open a ticket
2 rename of retopic the ticket 
3 rename of retop the ticket again
4 it won't rename or retopic it the second time and you can't close the ticket anymore white -close

**Expected behavior**
you shoud be able to rename or retopic the ticet multipele times and close the after that 

**Screenshots**
screenshot are not necessary i think

**Comment by eartharoid** [comment]
Is there an error when you try to rename or change the topic again? I think this is most likely due to rate-limiting.

**Comment by QuintenQVD0** [comment]
no it just give the embed off succes and no errors in the consol. 
if it's and error du to rate-limiting how to i fix this?
I use MSQL

**Comment by eartharoid** [comment]
If it is caused by Discord's rate limits you just need to wait longer between renaming it the first and second time.
