### ISSUE TITLE
Error when people react the embed

### ISSUE THREAD

**Issue by maximainero** [discord-tickets/bot#142]
**Describe the bug**
When the people react the embed nothing call the event messageReactionAdd, so the emoji up to 2 and doesnt create a new ticket
 Help!

**Comment by soudblox** [comment]
Is there any errors? Does the bot have permission to create channels? Is the bot online?

**Comment by maximainero** [comment]
Hello, yes, I guess it was the latest version of the bot that was the error download version 2.0 and now is running ok.. Another question.. do you know how to add more toppics-channels?

**Comment by soudblox** [comment]
Ah, yes latest version is not done. And what do you mean by topics-channels?

**Comment by itzJOHv** [comment]
panel reaction will create a ticket if:
- client is up and running
- panel is set correctly
- bot has acces to the channel
