### ISSUE TITLE
Add support for buttons

### ISSUE THREAD

**Issue by eartharoid** [discord-tickets/bot#163]
Add a `--butons` (`-b`) flag to the `panel` command which causes the reaction panel to use buttons instead.

- For single-category panels:
    ```
    -panel
    -t "example"
    -b "Create your ticket"
    -c <id>
    ```

    would do the same as the current code but add a button with the specific text rather than a reaction. The bot needs to check that if there is only one `-c` flag, there *must** be button text provided.
- For multi-category panels:
    ```
    -panel
    -t "example"
    -b
    -c <id>
    -c <id>
    ```

    Instead of the same number of `-e` and `-c` flags, a single `-b` flag is provided _without any text_, along with multiple `-c` flags. This would produce an embed similar to the current one but without the `:emoji: | category name` text. The button text is the category name, and the buttons should be in the order of the `-c` flags.

**Comment by thevisuales** [comment]
Hi there! this is not implemented yet, right?

**Comment by eartharoid** [comment]
Not yet. soon :tm:

**Comment by Mbarmem** [comment]
Any ETA on this?

**Comment by eartharoid** [comment]
Within a month maybe.

**Comment by eartharoid** [comment]
Fully transitioned to buttons (on [slash-commands](https://github.com/discord-tickets/bot/tree/slash-commands) branch). Also added `image` and `thumbnail` options for panels. Will be released when the last few commands are converted to slash commands.
