### ISSUE TITLE
Add a log channel

### ISSUE THREAD

**Issue by eartharoid** [discord-tickets/bot#170]
Optionally send a message to a channel with a ticket is opened, closed, or claimed.

**Comment by mon5termatt** [comment]
will this include transcripts

**Comment by eartharoid** [comment]
no

**Comment by eartharoid** [comment]
Events to log:
- [user] created ticket (in category)
- [user] edited/deleted message (in ticket)
- [staff] claimed/unclaimed (ticket)
- [admin] created/updated/deleted category/server etc
