### ISSUE TITLE
Tickets bot creates channel with old username

### ISSUE THREAD

**Issue by moo-sek-freak** [discord-tickets/bot#172]
Whenever I make a ticket it opens the channel with a username I haven't used for about a year, it's very annoying and confuses the ticket answerers

**Comment by eartharoid** [comment]
I don't see how it's possible for it to use an incorrect username. Although, the bot uses the [user's username](https://discord.js.org/#/docs/main/stable/class/User?scrollTo=username), not the member's nickname.
