### ISSUE TITLE
[BUG] Can't close ticket if member left

### ISSUE THREAD

**Issue by mon5termatt** [discord-tickets/bot#173]
**Describe the bug**
If the user has left the guild you cannot close the ticket

**To reproduce**
have user leave. attempt to close ticket....

**Expected behaviour**
close the ticket

**Screenshots**
[Short Video](https://cdn.mon5termatt.club/wl/?id=NeO6mryBgX8s8f6ukQPK1B7HVuoDC8yr)

**Comment by malavancs** [comment]
Does anyone started working on this ?. If not , you can assign to me.

**Comment by eartharoid** [comment]
@malavancs you can have a go at fixing this if you want. I think that the bot is meant to automatically close tickets when the member leaves anyway, which would mean this issue shouldn't be possible, but clearly, that didn't work. Want to try fixing that too?

**Comment by eartharoid** [comment]
Fixed in https://github.com/discord-tickets/bot/commit/5606071daac162944ffc36a3bc4d6814ffbc71a2.
