### ISSUE TITLE
[BUG] Mysql

### ISSUE THREAD

**Issue by PMTSantos** [discord-tickets/bot#180]
When I put in DB_TYPE mysql always shows the same error in the terminal. I don't know if I need to do something or if it's a configuration error. Foto:
![image](https://user-images.githubusercontent.com/81629693/124466870-ffb3cc80-dd8e-11eb-937f-0af40ac8ec73.png)

**Comment by eartharoid** [comment]
![image](https://user-images.githubusercontent.com/20905071/124467177-689b4480-dd8f-11eb-814d-449421bcf017.png)

https://discordtickets.app/installation/#standard-installation

**Comment by PMTSantos** [comment]
I did everything as shown in the image, but I still have an error.
![image](https://user-images.githubusercontent.com/81629693/124480280-01858c00-dd9f-11eb-86ea-f9e3d1562baa.png)

**Comment by eartharoid** [comment]
Your MySQL server is not accepting connections on `127.0.0.1:3306`, it's not a problem with the bot.

**Comment by PMTSantos** [comment]
Do you know if there is any way to solve it?

**Comment by itzJOHv** [comment]
> Do you know if there is any way to solve it?

make ur mysql server to accept 127.0.0.1 connections
