### ISSUE TITLE
[BUG] Discord token in .env

### ISSUE THREAD

**Issue by MCCZexe** [discord-tickets/bot#187]
**Describe the bug**
When entering the token to the .env file, console says that the token is missing

**To reproduce**
1. update node to newer version
2. paste the token in the .env file
3. run the program

**Expected behaviour**
To have setuped the bot.

**Screenshots**
![20210717_113830](https://user-images.githubusercontent.com/72745682/126032937-c567a939-8f9d-44ea-9778-2774d41b33c7.jpg)
![20210717_124510.jpg](https://user-images.githubusercontent.com/72745682/126034475-ba8b6b8d-a735-4a3c-8c80-ad889d6f02e2.jpg)

**Additional context**
Using repl.it with updated node

**Comment by iSamuelCO** [comment]
You are entering the token wrong.

**Comment by MCCZexe** [comment]
> You are entering the token wrong.

Then tell me how please

**Comment by Aquatic-Animation** [comment]
You should Go to Commands and To Secrets and Add The Key [TOKEN] Value [YOUR TOKEN HERE]
