### ISSUE TITLE
Problem with Pterodactyl egg

### ISSUE THREAD

**Issue by ItzKazuki** [discord-tickets/bot#198]
![Screenshot_2021-08-11-13-15-36-784_com android chrome](https://user-images.githubusercontent.com/79141593/128978937-aea08967-bae0-4367-ab83-344bbf2fb336.jpg)

do you know how to fix this, I tried using the pterodactyl egg that comes with this ticket github :)

**Comment by eartharoid** [comment]
It looks like it's working.

I don't know how to fix the entrypoint.sh error; the egg works perfectly for me without this error, unless I missed it.
