### ISSUE TITLE
[BUG] Cannot set property 'claiming' of null

### ISSUE THREAD

**Issue by eartharoid** [discord-tickets/bot#199]
**Describe the bug**

This error occurs when creating a new category with all of the properties

**To reproduce**

Create a new category with all of the properties

**Expected behaviour**

**Screenshots**

**Additional context**

Might only be when `claiming` is present but could affect other properties too

**Comment by JoeAshworth** [comment]
+1 on this

**Comment by eartharoid** [comment]
Should be resolved due to new settings command (slash-commands branch).
