### ISSUE TITLE
[BUG] replit .env

### ISSUE THREAD

**Issue by kittylegitcheck2** [discord-tickets/bot#218]
Here are images:
![Screenshot_2021-08-23-19-51-33-32](https://user-images.githubusercontent.com/82405746/130493809-902f2c4c-d9ac-482e-8d57-d43c7cf553a7.jpg)
![Screenshot_2021-08-23-19-50-55-49](https://user-images.githubusercontent.com/82405746/130493810-47d0e750-3afc-4f44-9bb6-9c19d05dd082.jpg)
Also i entered token correctly

**Comment by eartharoid** [comment]
The bot doesn't work on replit because it checks for the `./.env` file on startup. Replit replaces this file with the environment variables tab of the sidebar, so the bot will never start.
