### ISSUE TITLE
[BUG] Panels don't work with custom emoji

### ISSUE THREAD

**Issue by MisterMelDev** [discord-tickets/bot#229]
**Describe the bug**
When using custom emoji in a ticket create panel, the ticket fails to create. The reaction will be removed from the panel, but no ticket is created. No console output.

**To reproduce**
1. Add one or more custom emoji to a guild
2. Create a panel with that emoji as a reaction option
3. Attempt to create a ticket, it won't work

**Expected behaviour**
The ticket to be created as is normally the case.

**Comment by eartharoid** [comment]
Emoji/reaction panels have been replaced with button/select menus.
