### ISSUE TITLE
[BUG] DiscordAPIError: Missing Access

### ISSUE THREAD

**Issue by KINGK0NG-V1** [discord-tickets/bot#244]
Big problem, error with DiscordApi look the screen

![image](https://user-images.githubusercontent.com/52496524/135122570-4b5c9155-e1b5-488b-b212-08727f7570c7.png)

**Comment by eartharoid** [comment]
This isn't a bug.
Re-add the bot to your Discord server using the invite generator at [discordtickets.app/invite-url-generator](https://discordtickets.app/invite-url-generator/) to allow the bot to create application (slash) commands.
