### ISSUE TITLE
Defer interaction responses

### ISSUE THREAD

**Issue by eartharoid** [discord-tickets/bot#250]
#### Problem

On slow connections/servers the reply token expires before the bot is ready, resulting in a `DiscordAPIError: Unknown interaction` error and the interaction failing (usually after the bot has already started doing something).

#### Solution

Defer the reply immediately (in the command handler method), and update the reply in the command execution.

**Comment by anondev-sudo** [comment]
Upvote, I have this problem

**Comment by eartharoid** [comment]
Uses deferred replies where possible, also added caching in some areas - could add more if times out are still an issue.
