### ISSUE TITLE
[BUG] Cryptr: secret must be a non-0-length string

### ISSUE THREAD

**Issue by AceKiller250** [discord-tickets/bot#256]
**Describe the bug**

Console getting an error.
**To reproduce**

Run it on linux.
**Expected behaviour**

To work
**Screenshots**

**Additional context**

```
Cryptr: secret must be a non-0-length string
```
21.11 04:20:23 [Bot] 2021-11-21 09:20:23 [NOTICE] PLEASE INCLUDE THIS INFORMATION IF YOU ASK FOR HELP ABOUT THE FOLLOWING ERROR:
21.11 04:20:23 [Bot] 2021-11-21 09:20:23 [NOTICE] Discord Tickets v3.1.3, Node v16.7.0 on linux
21.11 04:20:23 [Bot] 2021-11-21 09:20:23 [] An error was not caught
21.11 04:20:23 [Bot] 2021-11-21 09:20:23 [] Uncaught Error
21.11 04:20:23 [Bot] 2021-11-21 09:20:23 [ERROR] Error: Cryptr: secret must be a non-0-length string
21.11 04:20:23 [Bot] at new Cryptr (/Bot2/node_modules/cryptr/index.js:12:15)
21.11 04:20:23 [Bot] at /Bot2/src/index.js:142:18
21.11 04:20:23 [Bot] at new Bot (/Bot2/src/index.js:185:5)
21.11 04:20:23 [Bot] at Object.<anonymous> (/Bot2/src/index.js:217:1)
21.11 04:20:23 [Bot] at Module._compile (node:internal/modules/cjs/loader:1101:14)
21.11 04:20:23 [Bot] at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
21.11 04:20:23 [Bot] at Module.load (node:internal/modules/cjs/loader:981:32)
21.11 04:20:23 [Bot] at Function.Module._load (node:internal/modules/cjs/loader:822:12)
21.11 04:20:23 [Bot] at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:79:12)
21.11 04:20:23 [Bot] at node:internal/main/run_main_module:17:47
```

**Comment by eartharoid** [comment]
This isn't a bug; if you follow the instructions at https://discordtickets.app/installation/standard/, this will not happen.
When you run the bot whilst `.env` does not exist, it will generate the encryption key and save it to `.env`.
