### ISSUE TITLE
[FEATURE REQUEST] Configurable setting for number of tickets allowed to be opened per user

### ISSUE THREAD

**Issue by missionz3r0** [discord-tickets/bot#277]
**Current Functionality**

A user can only have one ticket open at a time. 

**Requested Functionality**

- Add configurable setting for number of allowed tickets per user.
  - Setting the value to 0 would allow users to submit without limits
- Add command to set value.
- Change logic to use setting to allow multiple tickets to be submitted.

**Comment by eartharoid** [comment]
This already exists - `/settings categories edit id: ... max_per_member: ...`. There isn't an unlimited option anything above a reasonable number of tickets will have the same effect.
