### ISSUE TITLE
[DOCUMENTATION ERROR] Misspelling on discordtickets.app/plugins/#creating-a-plugin

### ISSUE THREAD

**Issue by RooRay** [discord-tickets/bot#283]
**Describe the bug**
There is a misspelling on https://discordtickets.app/plugins/#creating-a-plugin where the sentence:
> Official plugins are those that are officially maintained and supported. Additional community plugins can add features that meat more specific needs.
uses the word "meat" instead of "meet" which is a spelling mistake.

**To reproduce**
go to and observe it yourself https://discordtickets.app/plugins/#creating-a-plugin

**Expected behaviour**
eartharoids spelling is better

**Screenshots**
![image](https://user-images.githubusercontent.com/86845749/160674944-fb0b9b54-37f3-4d90-b850-4f63eb2b83fb.png)

**Additional context**
git gud @ spelling eartharoid :kekw:

**Comment by eartharoid** [comment]
Fixed in https://github.com/discord-tickets/docs/commit/e8d80aa82cc23277677da02e8e1af9ccca43dfe5.
