### ISSUE TITLE
[BUG] Permissions

### ISSUE THREAD

**Issue by UnknownOre** [discord-tickets/bot#284]
**Describe the bug**

It says i don't have permissions whenever i try to use /panel, even tho im the guild owner

**To reproduce**

**Expected behaviour**

**Screenshots**

**Additional context**

**Comment by RooRay** [comment]
this is not a bug, its an issue with your configuration

you dont have the staff role of the category/categories you made. go fix that or get help in the discord server rather than making "bug" reports
