### ISSUE TITLE
Ticket questions modal

### ISSUE THREAD

**Issue by eartharoid** [discord-tickets/bot#309]
When modals are supported, add a category `questions` option - an array of questions to be asked **before** the ticket is created.

**Comment by eartharoid** [comment]
**Post details:**
* Author: `eartharoid`
* Votes amount: `3`
* Comments amount: `0`

See full discussion at ![](https://cdn.feedbacky.net/static/img/logo-16.png) Feedbacky [here.](https://app.feedbacky.net/i/ticket-questions-modal.4271)

**Comment by anondev-sudo** [comment]
Good idea
