### ISSUE TITLE
[BUG] [ERROR] DiscordAPIError: 405: Method Not Allowed

### ISSUE THREAD

**Issue by Ryan732** [discord-tickets/bot#315]
[ERROR] DiscordAPIError: 405: Method Not Allowed
    at RequestHandler.execute (C:\Users\admin\bot\node_modules\discord.js\src\rest\RequestHandler.js:350:13)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async RequestHandler.push (C:\Users\admin\bot\node_modules\discord.js\src\rest\RequestHandler.js:51:14)
    at async ApplicationCommandPermissionsManager.set (C:\Users\admin\bot\node_modules\discord.js\src\managers\ApplicationCommandPermissionsManager.js:186:18)
    at async C:\Users\admin\bot\src\modules\commands\manager.js:137:5
    
    have this occuring, for some tickets members are not added to them. though for other tickets it works perfectly fine

**Comment by Ryan732** [comment]
on top of that this error is also showing up

(node:9096) DeprecationWarning: Passing strings for MessageEmbed#setAuthor is deprecated. Pass a sole object instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
(node:9096) DeprecationWarning: Passing strings for MessageEmbed#setFooter is deprecated. Pass a sole object instead.

**Comment by eartharoid** [comment]
This error shouldn't stop anything from working and has already been "fixed" in https://github.com/discord-tickets/bot/commit/2ea78a1457a3dfbf3bc3043feeb7d2b449d25585.

Some members not being added to their tickets is an unrelated issue. If there's not a relevant error, try:
- re-add the bot [with this link](https://discordtickets.app/invite-url-generator/)
- move the bot's role to the top of the role list.


You can ignore the deprecation warnings.

**Comment by Ryan732** [comment]
> This error shouldn't stop anything from working and has already been "fixed" in [2ea78a1](https://github.com/discord-tickets/bot/commit/2ea78a1457a3dfbf3bc3043feeb7d2b449d25585).
> 
> Some members not being added to their tickets is an unrelated issue. If there's not a relevant error, try:
> 
> * re-add the bot [with this link](https://discordtickets.app/invite-url-generator/)
> * move the bot's role to the top of the role list.
> 
> You can ignore the deprecation warnings.

tried re-adding it and that only made it now so I can't use the / commands

**Comment by eartharoid** [comment]
That's a Discord issue.

Join [go.eartharoid.me/discord](https://go.eartharoid.me/discord) then look at this for a solution: https://ptb.discord.com/channels/451745464480432129/970146229243760730/970470931728314378
