### ISSUE TITLE
[BUG] An error occurred whilst publishing the commands on every start

### ISSUE THREAD

**Issue by FoxXxHater** [discord-tickets/bot#317]
**Describe the bug**
When you start the bot this error is posted to the console.

The commands are also not displayed in Discord in the slash list

**To reproduce**
Was freshly installed, so no

**Expected behaviour**
That it works XD

**Screenshots**
<img width="1083" alt="image" src="https://user-images.githubusercontent.com/54017453/170042004-c75c7cb9-a1d3-4c38-b1e1-39675e7d9890.png">

**Additional context**
There is no further information

**Comment by eartharoid** [comment]
Discord doesn't allow non-English characters in command/option names. This will be fixed with the new command localisation system in v4.

Set the global locale in the config file back to `en-GB` to fix commands, then change the guild locale to whatever you want later with `/settings set locale:`
