### ISSUE TITLE
[BUG] Websocket was closef before the connection was established

### ISSUE THREAD

**Issue by FoxXxHater** [discord-tickets/bot#318]
**Describe the bug**
The bot crashed

**To reproduce**
Nothing

**Expected behaviour**
Fix it

**Screenshots**
![image](https://user-images.githubusercontent.com/54017453/171558553-e64a82bc-0368-4455-8b6b-9217e34c4788.png)

**Additional context**
The World is sometimes great...?!

**Comment by eartharoid** [comment]
Is your pi connected to the internet?

**Comment by RooRay** [comment]
this is not a bug, its an issue with your installation. use [the support discord server](https://discord.com/invite/nMrWd8aZaP) or github discussions instead of opening issues please

**Comment by FoxXxHater** [comment]
Okay... 
But yes the pi is connected. After restarting the bot, it did not crash again. It was apparently the first and (hopefully) the last time. 

Could have been perhaps a DNS or an Internet error...
Because the server hosts several bots / services
