### ISSUE TITLE
Add *DM* support

### ISSUE THREAD

**Issue by xDope7137** [discord-tickets/bot#328]
The main issue with tickets is, that users always forget to come back and see new messages in tickets. The best way to avoid this would be a DM ticket system.

Where moderators can somehow interact with users via a bot. I have seen it on a server so it is possible. I don't know how does the moderators reply to the messages, but the idea is pretty cool.

**Comment by eartharoid** [comment]
Oops, confused this with #296.

Users will be able to create a ticket by sending a DM (#296), but interacting via DMs (having a conversation *through* the bot) won't be added.
If you really want this, try https://github.com/Dragory/modmailbot or https://github.com/kyb3r/modmail.

Some features are planned that should solve the problem of users not replying though:

- #305 (will ping the user in the ticket, DMs could be added later too if users are ignoring server pings)
- #299
