### ISSUE TITLE
Unable to add opening_questions to tickets

### ISSUE THREAD

**Issue by SoNotMC** [discord-tickets/bot#335]
**Describe the bug**
When trying to add opening questions to a category I am just told an unexpected error occured

**To reproduce**
Do /settings categories edit <id> opening_questions:<questions>

**Expected behaviour**
It should set the questions and then upon opening a ticket with this category it should send the question

**Screenshots**
https://i.e-z.host/zg1qlq3s.png
https://i.e-z.host/7x9punl5.png

**Comment by itzJOHv** [comment]
what did you enter in `opening_questions` option? make sure its in format of `["question 1", "question 2", "another question"]`

**Comment by SoNotMC** [comment]
Ohh sorry. It dosent have a guide of any sort so I was unable to know to put that.

**Comment by eartharoid** [comment]
A new way of setting questions coming soon:

![](https://cdn.discordapp.com/attachments/815914336316948531/999814734897500190/unknown.png)
