### ISSUE TITLE
[BUG] Claim button not working

### ISSUE THREAD

**Issue by SoNotMC** [discord-tickets/bot#339]
**Describe the bug**
When clicking the claim button in a ticket it just says that the interaction failed.

**To reproduce**
Open a ticket and then click claim as an admin.

**Expected behaviour**
It should claim the ticket successfully. 

**Screenshots**
![Discord_WVyqIbvdxD](https://user-images.githubusercontent.com/43901997/190214920-952dfe38-d90b-435d-9ae2-671ea83b1b09.png)

**Comment by eartharoid** [comment]
Oops, missed this.

If you're still having this problem, is there an error in console when you use the button?
It's likely that the bot didn't respond fast enough, so if you try again it might work.
