### ISSUE TITLE
[BUG] Text Transcripts Plugin Not Displaying Text

### ISSUE THREAD

**Issue by jak64950** [discord-tickets/bot#343]
The text transcripts plugin will save a blank archive of the ticket conversation. Screenshot better explains the issue.

Using v3.1.3 self hosted on an Oracle Cloud Instance with mysql db

![bug](https://user-images.githubusercontent.com/39564839/192428557-5bb0181c-272f-4d9a-b7f6-af8682fc50e3.PNG)

**Comment by eartharoid** [comment]
Make sure you have the message content intent enabled on the bot page at https://discord.com/developers/applications, then restart the bot.

If it is already enabled, are there any errors is console when people send messages in tickets?

**Comment by jak64950** [comment]
How silly of me, that was it! Thank you so much.
