### ISSUE TITLE
[BUG] fr-FR locale doesn't work

### ISSUE THREAD

**Issue by thomasbonsirven** [discord-tickets/bot#345]
**Describe the bug**
Change local to fr-FR, the bot not work
**To reproduce**
Change the locale to fr-FR

**Comment by eartharoid** [comment]
If you are talking about the `locale` option in `user/config.js`, this is a known issue - it's because Discord doesn't allow special (accented) characters in the command names. Use `en-GB` as the global locale and change it in your Discord server instead:
`/settings set locale: fr-FR`.

**Comment by thomasbonsirven** [comment]
Yes, that's what I was talking about.

But it doesn't always work, very few texts are translated.
But in the .json it is well translated, an idea where there is nothing to do?

**Comment by eartharoid** [comment]
The command names and descriptions will be in English but if you've changed the server's locale to fr-FR, (almost) everything else should be using that file (for command responses etc).
What else is in English?
