### ISSUE TITLE
[BUG] /botinfo not working

### ISSUE THREAD

**Issue by sadoj-kuro** [discord-tickets/bot#350]
When i type /botinfo he say me not respond. i think the commande its broken

**Comment by eartharoid** [comment]
botinfo is not a command.

**Comment by sadoj-kuro** [comment]
![image](https://user-images.githubusercontent.com/8905889/195003927-273a6bf2-66f4-44e4-bad0-e56ff9b7db18.png)
euuu ? why i have this commande from the bot o.O

**Comment by eartharoid** [comment]
Did you reuse the bot application from a previous bot?

**Comment by sadoj-kuro** [comment]
yes, that for that ?

**Comment by eartharoid** [comment]
`/botinfo` isn't part of Discord Tickets so it must be from something else.
