### ISSUE TITLE
Add myself as a contributor - created a working docker container with docu

### ISSUE THREAD

**Issue by FoxXxHater** [discord-tickets/bot#367]
@all-contributors please me (@foxxhater) for creating a working docker image. 

You can find any Informations in my repo.

Thanks

**Comment by RooRay** [comment]
@all-contributors please add @FoxXxHater for platform

**Comment by RooRay** [comment]
You need to use [contribution types](https://allcontributors.org/docs/en/emoji-key) for the all-contributors bot. Since you made a working dockerfile, I requested to add you as a contributor for the platform category since it’s the most applicable.

**Comment by FoxXxHater** [comment]
what do you mean?

i would mean „platform“?

**Comment by FoxXxHater** [comment]
upps.. i wouldnt close the issue…

but what did you mean?

i would say „platform“?

**Comment by RooRay** [comment]
> upps.. i wouldnt close the issue…
> 
> but what did you mean?
> 
> i would say „platform“?
> 
> thanks

Platform is used on the all contributor when referring to porting the code to other platforms, since you ported it to Docker, the platform category would be most suitable.

**Comment by FoxXxHater** [comment]
Okay... 
I don't know much about GitHub and the whole thing. I am glad that I have managed to do all this at all. XD
But i have retored the contribution files in my repo

**Comment by eartharoid** [comment]
@FoxXxHater thanks for improving the Dockerfile, but it would be better if you created a pull request so your changes can be merged back into this repository.
Although, there is already a PR (#360) that I forgot about but is much more complete and has a compose file.
Would you like to test or write a bit of documentation for #360 so I can merge it and add you both as contributors?

**Comment by FoxXxHater** [comment]
Hay,
thank you for the answer. But I have created my containers based on the existing (but not complete) dockfile but I have done everything on my own and I have already pulled it onto the Docker Hub. 
I also already have documentation (https://wiki.foxco-network.de/en/docker-portainer/install-discord-tickets-bot).

I am happy to write a docker compose file and present it in my repo.

**Comment by FoxXxHater** [comment]
Hey Issac,

If it is necessary, I think it is useful to link my documentation in the official docu.

**Comment by RooRay** [comment]
> Hey Issac,
> 
> If it is necessary, I think it is useful to link my documentation in the official docu.

If you want you can also [add it to the official documentation](https://github.com/discord-tickets/docs/edit/main/docs/installation/docker.md) and then make a Pull Request with your changes.

**Comment by eartharoid** [comment]
Added in https://github.com/discord-tickets/docs/commit/f5bdd41b610603def58dd3390f0383a6428bf70f

**Comment by RooRay** [comment]
> Added in [discord-tickets/docs@f5bdd41](https://github.com/discord-tickets/docs/commit/f5bdd41b610603def58dd3390f0383a6428bf70f)

Would it not be better to incorporate it into the official docs so we're not relying on a third party docs site? Especially since it's down right know 😄

**Comment by eartharoid** [comment]
no

**Comment by FoxXxHater** [comment]
> Would it not be better to incorporate it into the official docs so we're not relying on a third party docs site? Especially since it's down right know 😄


Yes because DNS's are shit... but now its online
