### ISSUE TITLE
Docker images

### ISSUE THREAD

**Issue by eartharoid** [discord-tickets/bot#372]
Use https://github.com/marketplace/actions/build-and-push-docker-images?

**Comment by c43721** [comment]
@eartharoid 

docker/metadata-action@v3
docker/login-action@v1
docker/build-push-action@v2

You'll want to look into these three actions, and I can show you a workflow of how I push to github packages.

**Comment by eartharoid** [comment]
- https://docs.github.com/en/actions/publishing-packages/publishing-docker-images
- https://docs.docker.com/language/nodejs/configure-ci-cd/

**Comment by eartharoid** [comment]
Added in https://github.com/discord-tickets/bot/commit/b2de472329aa6ae6f861729a0099ec23593adde9, don't know if it works yet,
