### ISSUE TITLE
[BUG] Permissions error with Docker compose

### ISSUE THREAD

**Issue by ScribblerCoder** [discord-tickets/bot#374]
**Describe the bug**
`node` user doesn't have read permission to `example.config.js` and no write permissions to `/tickets/user/` directory

**To reproduce**
Run the bot using `docker-compose up`

**Detailed Error logs**
```
Copying "./user/example.config.js" to "./user/config.js"...
node:internal/fs/utils:347
    throw err;
    ^

Error: EACCES: permission denied, copyfile '/tickets/user/example.config.js' -> '/tickets/user/config.js'
    at Object.copyFileSync (node:fs:2847:3)
    at checkFile (/tickets/src/index.js:43:5)
    at Object.<anonymous> (/tickets/src/index.js:47:1)
    at Module._compile (node:internal/modules/cjs/loader:1165:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1219:10)
    at Module.load (node:internal/modules/cjs/loader:1043:32)
    at Function.Module._load (node:internal/modules/cjs/loader:878:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:22:47 {
  errno: -13,
  syscall: 'copyfile',
  code: 'EACCES',
  path: '/tickets/user/example.config.js',
  dest: '/tickets/user/config.js'
}
```
**Suggestion**

Instead of accessing `./src` and `./user` using volumes, they could be copied inside the docker image during building the image.

@eartharoid 

P.S   I could create pull request if needed. I love your work btw and have been waiting for Dockerised and docker-compose version of this discord bot

**Comment by eartharoid** [comment]
You can submit a PR if you know how to fix it, but doesn't it make sense to use volumes at least for `./user` so you don't need to rebuild to change the config file?

**Comment by ScribblerCoder** [comment]
> 

good point, I guess I could stick to removing the src/ volume and will do some more research on how docker sets permissions for mounted volumes

**Comment by eartharoid** [comment]
You need to fork the repository (https://github.com/discord-tickets/bot/fork) and then you can commit to the main branch on yours.

**Comment by ScribblerCoder** [comment]
I've done my homework and I see that we shouldn't be really giving permissions of a mounted volume to a non-root user nor give write permissions to a non-owner user (it doesn't make sense). We can simply instead create a simple bash script that copies the `example.config.js` to `config.js` and create random db encryption key. Or simply we can write these steps in the docs under the docker installation section.

**Comment by eartharoid** [comment]
> We can simply instead create a simple bash script that copies the `example.config.js` to `config.js` as `root/home` user

Can't this be done in the Dockerfile without a separate script? Either way, it's probably better to add a step to the docs to tell the user to copy/rename the config file themselves.

I think the encryption key should be set in the compose file (as generating a new key each time the image is built would mean you need to reset the database), so that's another documentation problem.

https://github.com/discord-tickets/bot/blob/6a1a75d572509632742f7be68eef0376c54ed495/docker-compose.yml#L14-L21

**Comment by ScribblerCoder** [comment]
I couldn't agree more! I beleived that  it was a design choice to not set the encryption key in the docker-compose environmental variables even though other variables like DB_TYPE is being clearly set.

**Comment by ScribblerCoder** [comment]
The script can check if the key has been set or not before resetting it*

**Comment by eartharoid** [comment]
Dockerfile works on v4.

**Comment by alf1e** [comment]
Hey!
I seem to be getting this error again.
```
Error: EACCES: permission denied, mkdir 'user/uploads'
    at mkdirSync (node:fs:1391:3)
    at mkDirAndCopy (node:internal/fs/cp/cp-sync:268:3)
    at onDir (node:internal/fs/cp/cp-sync:263:25)
    at getStats (node:internal/fs/cp/cp-sync:167:12)
    at copyDir (node:internal/fs/cp/cp-sync:284:21)
    at onDir (node:internal/fs/cp/cp-sync:264:10)
    at cpSyncFn (node:internal/fs/cp/cp-sync:61:10)
    at checkParentDir (node:internal/fs/cp/cp-sync:159:10)
    at Object.cpSync (node:fs:3020:3) {
  errno: -13,
  syscall: 'mkdir',
  path: 'user/uploads'
  code: 'EACCES',
}
```
