### ISSUE TITLE
[BUG] move slash-command returns TypeError

### ISSUE THREAD

**Issue by thecmdradama** [discord-tickets/bot#381]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When attempting to move a ticket from one category to another, I had gotten the following error with the first ticket I attempted to move

[ERROR] (COMMANDS) "move" command execution error: TypeError: Cannot read properties of undefined (reading 'total')
    at MoveSlashCommand.run (/var/lib/pufferpanel/servers/abb7ee01/src/commands/slash/move.js:91:4)

Subsequent tickets seem to be changing categories fine

### Expected Behavior

What I am expecting to see is that the name of the channel should change from "support-#" to "tech-#" and the list of users who can see the ticket should also be reduced to those with the tech role. Currently neither seem to happen either when the command fails or succeeds. 

### Steps To Reproduce

1. Create both a Support and Tech category and assign unique ticket prefixes for each category.
2. Create a ticket in the support category 
3. Run the /move slash command and attempt to move the ticket between the two categories.
4. Error should occur.

### Environment

```markdown
- OS: Ubuntu 22.04.1
- Node: 18.14.0 LTS
- NPM: 9.3.1
- Bot: v4.0.0-beta.3
```

**Comment by eartharoid** [comment]
https://github.com/discord-tickets/bot/blob/316de401602d0789e45d614ad39108ff660979b1/src/commands/slash/move.js#L88-L98

Looks like a caching problem

**Comment by eartharoid** [comment]
This error is caused by trying to move a ticket into a category that

- was created since the last cache sync (which happens at startup and when you type `sync` in console)
- and does not have any tickets

So to move a ticket into a category that you have just created, you either need to create a ticket in that category, or sync/restart the bot.

**Comment by thecmdradama** [comment]
Thanks for that, that would explain why it wouldn't work the first time and then worked every other attempt./

It would still be good if the moved ticket would update the members and channel prefix for that new category.

**Comment by eartharoid** [comment]
> It would still be good if the moved ticket would update the members and channel prefix for that new category.

Added in https://github.com/discord-tickets/bot/commit/a95330853203b1b035bd9cb66aaa48b3efa11b9f.
