### ISSUE TITLE
[BUG] Error when sending the command "commands publish"

### ISSUE THREAD

**Issue by Moldrok** [discord-tickets/bot#383]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

As in the attached images when trying to send the command in the bot's server console , the following error is returned : 

![image](https://user-images.githubusercontent.com/49076911/217387191-94ea4669-003f-41dd-9041-20918353fa72.png)
![image1](https://user-images.githubusercontent.com/49076911/217387202-69932d55-71bc-421d-a933-42ce357c5601.png)

### Steps To Reproduce

1. In console server run the command "commands publish"
2. The following error is returned in the console : "[ERROR] DiscordAPIError[50035]: Invalid Form Body
0.name_localizations.de[BASE_TYPE_BAD_LENGTH]: Must be between 1 and 32 in length."

### Environment

```markdown
- OS: Windows 11
- Node: 19.4.0
- NPM: 9.2.0
- Bot: 4.0.0-beta.3
```

**Comment by eartharoid** [comment]
This was caused by translations being too long or having uppercase characters.
