### ISSUE TITLE
[BUG] German Translation is broken, bot wont start. 

### ISSUE THREAD

**Issue by Tobias-Jung-DHBW** [discord-tickets/bot#390]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

In german, some letters are Upper case, which is vorbidden and therefore many commands wont work. Can you please fit it?

### Steps To Reproduce

Set Leanquage to de-DE

### Environment

```markdown
- OS:Windows
- Node:
- NPM:
- Bot: v3.1.3
```

**Comment by eartharoid** [comment]
Keep the locale in `user/config.json` as `en-GB` to make the commands English and then run `/settings set locale: de-DE` in your server to make the bot's responses German.

v4 (coming soon) supports translated commands (names, options, choices etc).
