### ISSUE TITLE
[BUG] 404 Error in /settings

### ISSUE THREAD

**Issue by BlutwurstPro** [discord-tickets/bot#391]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When i open <domain>/settings after i logged in, i get an 404 Error Page.
![image](https://user-images.githubusercontent.com/10463210/221173981-2534b993-d6f9-4f10-952b-2844fe4883ca.png)

### Expected Behavior

The settings page should open

### Steps To Reproduce

Setup the bot in an Node docker Container.

### Environment

```markdown
- OS: Debian 11
- Node: 19.6.0
- NPM: 9.4.2
- PNPM: 7.27.1
- Bot: 4.0.0 beta5
```

**Comment by eartharoid** [comment]
This is probably related to #379.

@BlutwurstPro could you see if this problem still occurs?
Pull the latest code and re-build the Docker image.
