### ISSUE TITLE
[BUG] After updating discord js

### ISSUE THREAD

**Issue by xrtw** [discord-tickets/bot#398]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

https://i.gyazo.com/53126d2452fd52c6dddb1cc9e9ec74f7.png

Shows this error when trying to close tickets

### Environment

```markdown
- OS: Win 10
- Node: 16.0
- NPM:
- Bot: 3.1.3
```

**Comment by eartharoid** [comment]
The deprecation warnings are fine, and the errors appear to be unrelated to updating.
Sometimes the bot doesn't respond in time but if you run the command again it should work.
