### ISSUE TITLE
[BUG] Deprecation notices

### ISSUE THREAD

**Issue by Netherwhal** [discord-tickets/bot#399]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

```
(node:1) DeprecationWarning: Passing strings for MessageEmbed#setAuthor is deprecated. Pass a sole object instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
(node:1) DeprecationWarning: Passing strings for MessageEmbed#setFooter is deprecated. Pass a sole object instead.
(node:1) DeprecationWarning: Guild#me is deprecated. Use Guild#members#me instead.
```

after upgrading discord.js to 13-lts (its working now, but it might break again at some point)

### Environment

```markdown
- OS:
- Node:
- NPM:
- Bot:
```

**Comment by eartharoid** [comment]
The deprecated features aren't removed until discord.js@14 and v4 of the bot passes objects instead of strings.
