### ISSUE TITLE
[BUG] [V4] Can not disconnect

### ISSUE THREAD

**Issue by Uzurka** [discord-tickets/bot#413]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Can't disconnect from the panel. Says the token has been revoked, but he's not.

### Expected Behavior

Click on my username make me log out

### Environment

```markdown
- OS: Debian / Docker
- Node: 
- NPM:
- Bot:
```

**Comment by eartharoid** [comment]
Fixed in #415.
