### ISSUE TITLE
[BUG] Timezone error

### ISSUE THREAD

**Issue by Gdanycz** [discord-tickets/bot#417]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When I choose the timezone Europe/Prague and set the time for today to 20:00, the ticket says the time is set to 22:00.
![image](https://user-images.githubusercontent.com/60316826/236280778-6a753f2a-efd1-4f9f-9f77-0968751e3d9b.png)
![image](https://user-images.githubusercontent.com/60316826/236280822-0bf535a9-f4b4-4b3f-bfa6-f6d3598cc197.png)

### Environment

```markdown
- OS:
- Node:
- NPM:
- Bot:
```

**Comment by eartharoid** [comment]
@Gdanycz is your PC's timezone Prague as well?

**Comment by Gdanycz** [comment]
> @Gdanycz is your PC's timezone Prague as well?
Yes
