### ISSUE TITLE
[BUG] We panel doesn't use discord message length limits

### ISSUE THREAD

**Issue by abola2** [discord-tickets/bot#423]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

![image](https://github.com/discord-tickets/bot/assets/81980535/ee328004-fa08-4b87-a93b-2c905b5971f7)

### Expected Behavior

https://discord.com/developers/docs/resources/channel#embed-object-embed-limits

### Steps To Reproduce

Login panel
Start create new panel
Description doesn't use discord max length.

**Comment by eartharoid** [comment]
Just realised I fixed this already https://github.com/discord-tickets/portal/commit/fc7d33769b9b69995e8c969981fc08253b3a7dc2
