### ISSUE TITLE
[BUG] V4 Required Role to Create a ticket

### ISSUE THREAD

**Issue by tchavei** [discord-tickets/bot#427]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When I set Role "A" as required to open a ticket, users that ONLY have role "A" can create Tickets. If I don't set any required roles to create a ticket, no user with any role can open a ticket.

### Expected Behavior

When I set required role "A" to create a ticket, I expect that any user that has AT LEAST role "A" can create a ticket. If I set no required role, then I expect that any user can create a ticket, regardless of roles.

### Steps To Reproduce

docker environment
set category in back portal. Define required role as "A". Have an user with role "A" and role "B" try to open a ticket. It will fail with error "Blocked"

### Environment

```markdown
- OS: Rocky Linux 8
- Node: v16.13.1
- NPM: 8.1.2
- Bot: v4.0.0
```

**Comment by tchavei** [comment]
Seems the block list interferes with the required roles list

**Comment by eartharoid** [comment]
@tchavei it is working as expected then?

**Comment by tchavei** [comment]
> @tchavei it is working as expected then?

Yes. I disabled the blocked list. Then everything started to work ok. Thank you
