### ISSUE TITLE
[BUG] Some errors cause memory leaks and crashes

### ISSUE THREAD

**Issue by eartharoid** [discord-tickets/bot#436]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

https://github.com/discord-tickets/portal/issues/5
Some uncaught errors don't end up being handled by the `unhandledRejection` listener and instead, cause 100% CPU and RAM usage.

Might be related to errors thrown in `.map()`, `.forEach()` etc.

### Expected Behavior

Errors should either be caught and handled correctly or be handled by the unhandled process event listeners without causing a problem.

### Environment

```markdown
- OS:
- Node:
- NPM:
- Bot: 4.0.3
```

### Anything else?

😢

**Comment by GameAreaCZ** [comment]
When I create a panel with only one category everything is working fine. When I take all 6 categories (so it will be a menu) and I choose whatever category to post a ticket in, it is starting using 100% cpu and more and more RAM and then it crashes without an error. Maybe is connected with this error?

**Comment by eartharoid** [comment]
@GameAreaCZ the CPU and memory usage increase would be this.
Are you sure it is just going from a button to a menu that changed though? It's more likely to be https://github.com/discord-tickets/portal/issues/5.

**Comment by GameAreaCZ** [comment]
Ofcourse you are right. It was exactly like that. Two from six categories that I have had that empty (not None but empty completely). I changed that to None and it is working.

Thank you very much.

**Comment by eartharoid** [comment]
This *might* have been fixed by https://github.com/discord-tickets/bot/commit/e8b95a2f3149fab08ed3c927f771d8ee4fad9d04

**Comment by eartharoid** [comment]
Appears to be fixed.
