### ISSUE TITLE
[BUG] Issue with stale checks

### ISSUE THREAD

**Issue by GeckoBoy84** [discord-tickets/bot#459]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Bot sometimes pings a specific staff member

### Expected Behavior

Bot should ping the staff role

### Environment

```markdown
- OS: Pterodactyl - Ubuntu Server 20.04
- Node: 18
- NPM: Unknown
- Bot: 4.0.6
```

### Anything else?

https://discord.com/channels/451745464480432129/893207320878776400/1129016254628372490

**Comment by RooRay** [comment]
> ### Anything else?
> https://discord.com/channels/451745464480432129/893207320878776400/1129016254628372490

![screenshot of eartharoid asking the user to open an issue](https://github.com/discord-tickets/bot/assets/86845749/7dafa6d6-bc7b-488c-8c47-818ff5c68b86)

For those not in the Discord server
