### ISSUE TITLE
[BUG] Saying "null" can cause an automatic tag reply

### ISSUE THREAD

**Issue by eartharoid** [discord-tickets/bot#484]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The bot sends tag replies when it shouldn't if the message contains "null".

### Steps To Reproduce

1. Enable auto-tag in all channels
2. Create a couple of tags, at least one should have no regex value
3. Say `null`

### Environment

```markdown
- OS:
- Node:
- NPM:
- Bot: 4.0.10
```

**Comment by itzwam** [comment]
Welcome to JavaScript Hell

i'm interested in helping with this issue if needed ;)

**Comment by eartharoid** [comment]
Hi, a PR would be appreciated.
It should be an easy fix.
