### ISSUE TITLE
[BUG] cant create category

### ISSUE THREAD

**Issue by WallcroftUK** [discord-tickets/bot#486]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Error 500

Failed to fetch dynamically imported module: http://104.197.32.164:8169/_app/immutable/chunks/10-5caf9e71.js (id=18ac74c49c8)

### Expected Behavior

cant create category

### Steps To Reproduce

1. try create category

### Environment

```markdown
- OS: Ubuntu 20.04
- Node: 18.0.0
- NPM: 7.6.3
- Bot: latest
```

### Anything else?

![image](https://github.com/discord-tickets/bot/assets/122221257/913c6e00-f597-465c-bba8-333ed4999931)

**Comment by eartharoid** [comment]
Caused by the browser blocking requests.
