### ISSUE TITLE
Web Page not working and showing a error

### ISSUE THREAD

**Issue by emmu123** [discord-tickets/bot#519]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

![image](https://github.com/discord-tickets/bot/assets/89377181/eb339c15-d0ba-4945-b885-3f93b4868c39)

Help me

### Expected Behavior

Web page not working 
![image](https://github.com/discord-tickets/bot/assets/89377181/122a24b1-6274-41d5-96a5-da815e490812)

### Steps To Reproduce

See error 
![image](https://github.com/discord-tickets/bot/assets/89377181/228dae9b-6e15-4d3f-a353-375f2e676935)

### Environment

```markdown
- OS: Ubuntu 22
- Node: 18
- NPM: Latest
- Bot: 4.1.3
```

### Anything else?

Nop

**Comment by eartharoid** [comment]
The warnings and errors shown are unrelated to the error page.
If it said 500 it would be a common problem but I don't know how you've got 403, I can only guess it's something to do with a reverse proxy. Can you join the [Discord server](https://lnk.earth/discord) and DM me?

**Comment by emmu123** [comment]
sry mistakly that server deleted :(
