### ISSUE TITLE
[BUG] Leak Tickets to team member which dont have access to the category

### ISSUE THREAD

**Issue by Luzifix** [discord-tickets/bot#555]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The /tickets and /transcript commands show tickets from categories where a team member dont have access

### Expected Behavior

The /tickets and /transcript commands show only tickets for categories where a team memeber have access for

### Steps To Reproduce

1. Create two roles
2. Create two categories and set role 1 to category 1 and role 2 to category 2
3. Create a ticket in both categories and close them
4. Call with a team member which have role 1 the /tickets command on the user which created the two tickets in the two categories and you can see both. The expected behavior is that the team member which have only one of the two roles can only see tickets from categorie 1

### Environment

```markdown
- OS:
- Node:
- NPM:
- Bot:
```

**Comment by eartharoid** [comment]
@all-contributors please add @Luzifix for bug
