### ISSUE TITLE
Permission overwrites

### ISSUE THREAD

**Issue by eartharoid** [discord-tickets/bot#56]
Currently, the bot will create tickets with specific permissions overwrites (deny everyone, allow the bot, allow the support_role, and allow the creator). It would be better if the bot didn't overwrite the permissions from the parent/category when setting the ticket channel's permisssions.

**Comment by NamVr** [comment]
Hello! I want to contribute, what should I do?

**Comment by eartharoid** [comment]
If you think you know how to do this well you can submit a PR with your solution. The bot still needs to set channel permissions, but not completely delete the permissions that would otherwise be inherited from the category channel.

**Comment by NamVr** [comment]
https://github.com/eartharoid/DiscordTickets/pull/55#issuecomment-711048336
Did you checked this?
I m really confused now.

**Comment by MichaelYogar** [comment]
Hi, if this is still an issue I can give this a go!

**Comment by eartharoid** [comment]
Thanks :)

**Comment by eartharoid** [comment]
Better explanation in #58 PR [comment](https://github.com/eartharoid/DiscordTickets/pull/58#issuecomment-713068624).

**Comment by eartharoid** [comment]
soon ™️
