### ISSUE TITLE
[BUG] Missing docker build for latest `v4.0.20`

### ISSUE THREAD

**Issue by Paillat-dev** [discord-tickets/bot#561]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

A docker build is missing for the latest release, `v4.0.20`, both on DockerHub and ghcr.io.

### Expected Behavior

Having a docker image marked as `latest`,`v4.0.20`,`v4` on at least one of the container registries

**Comment by eartharoid** [comment]
The build appears to be succeeding and the logs claim the images were uploaded, but clearly they weren't.

**Comment by Paillat-dev** [comment]
@eartharoid Is there any updates on this?

**Comment by eartharoid** [comment]
Not yet. I don't know what the problem could be as the credentials appear to be valid still.

**Comment by Paillat-dev** [comment]
Yeah besides by looking at the CI logs everything looks fine...

**Comment by shrunbr** [comment]
> Not yet. I don't know what the problem could be as the credentials appear to be valid still.

Are there any updates for this? The build is still not on docker hub.

**Comment by eartharoid** [comment]
I changed nothing but it's working again. v4.0.21 is available on Docker Hub and GHCR.
