### ISSUE TITLE
[BUG] not able to log in the settings panel

### ISSUE THREAD

**Issue by Froniz** [discord-tickets/bot#564]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

discord login screen looping and console filling with 
 22/09/24 21:16:35  [INFO] (HTTP) req-24 ********* GET /auth/login -+> 302 in 0.30ms
 22/09/24 21:16:37  [INFO] (HTTP) req-25 ********* GET /auth/callback -+> 303 in 342.0
 (ip removed because of privacy)
 Tried it on my VPS, Home pc, Home server, all the same result
 http://cdn.froniz.xyz/u/LSBr1E.png (screenshot of home pc console spamming)

### Expected Behavior

loading in panel

### Steps To Reproduce

Just redownloaded it and did the same install method on the guide and node . to start

### Environment

```markdown
- OS: Windows 11 Pro
- Node: v21.5.0
- NPM:10.2.4
- Bot: Latest(4.0.20)
```

**Comment by eartharoid** [comment]
I don't know exactly what the problem is but this is usually fixed by resetting the application's token and client secret.

**Comment by Froniz** [comment]
i changed the client secret 1 time

**Comment by Froniz** [comment]
if you want an video i can send

**Comment by Froniz** [comment]
http://cdn.froniz.xyz/u/YfD8vd.mp4

**Comment by eartharoid** [comment]
Can you try with a new Discord application?

**Comment by Froniz** [comment]
sure

**Comment by Froniz** [comment]
now it works, dident think that would work, but thanks!
