### ISSUE TITLE
Error: fetch failed

### ISSUE THREAD

**Issue by LorenzoAbA** [discord-tickets/bot#566]
i have the same problem and i’m getting the same error, i tried changing the http external to 127.0.0.1 but when i authorize the app it can’t open the 127.0.0.1 url of course what can i do?

_Originally posted by @LorenzoAbA in https://github.com/discord-tickets/bot/issues/562#issuecomment-2425164225_

**Comment by eartharoid** [comment]
Have you tried setting
```
HTTP_INTERNAL=http://127.0.0.1:8169
```
and the external IP in `HTTP_EXTERNAL`?

**Comment by LorenzoAbA** [comment]
I got it thanks
