### ISSUE TITLE
Using JSDocs comments more to help with development of the bot

### ISSUE THREAD

**Issue by OliverCordingl1** [discord-tickets/bot#87]
**Is your feature request related to a problem? Please describe.**
When developing on the bot, especially being new to the codebase, it may help to have tooltips with classes and functions which code editors have built-in. As there is not any documentation, people developing for the project and customising their bot may struggle to understand what is going on.

**Describe the solution you'd like**
By adding JSDocs to the functions, code editors such as VSCode are able to provide API documentation.
This wouldn't be difficult to implement, however, it would need to be updated whenever a change was made to the code in order to stay up to date. I don't at all mind working on this, as I know it may seem like a tedious task, but efforts will be nullified if they don't stay up to date.

**Describe alternatives you've considered**
The alternative is that it stays as it is. However, providing (even vague) documentation can help inspire more contributors to work on the bot, as well as giving a helpful reminder to anybody already working on the bot.

**Additional context**
<img width="335" alt="Example of a tooltip that is generated with JSDocs" src="https://user-images.githubusercontent.com/19516518/104765120-4de0ff00-5760-11eb-8b3c-5d052e44750e.png">

**Comment by eartharoid** [comment]
Ok, I'll add comments and perhaps a brief overview of how it works in the documentation when I make v3 to help anyone contributing to or expanding upon the bot.

**Comment by OliverCordingl1** [comment]
Awesome. I don't mind helping out with that, I have used this in the past for my own custom needs and have tinkered with the code so I'm pretty familiar with most of it.

On an unrelated note, can I ask what happens with PRs and the version of the project? I have a pull request I'm gonna send in soon, just need to do some testing and optimisation.

**Comment by eartharoid** [comment]
Most of the code on the [master branch](https://github.com/discord-tickets/bot/tree/master) has JSDoc comments now. 👍
